services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: reminisce-registry
    ports:
      - "4873:4873"
    volumes:
      - ./.verdaccio/config.yaml:/verdaccio/conf/config.yaml
      - ./.verdaccio/storage:/verdaccio/storage
    environment:
      - VERDACCIO_PORT=4873
